package nl.tudelft.birthdayattack.utils

enum class PackageType {
    CONNECTION_INITIATION,
    CONNECTION_MAINTENANCE,
    BANDWIDTH_MEASUREMENT,
    TIMEOUT_MEASUREMENT,
    CONNECTION_ESTABLISHED
}